export let allProducts = [
  {
    id: 1,
    category: "Kids",
    name: "Yellow T-Shirt",
    price: 180,
    inventory: 15,
    img: "././images/product1.png",
    qty: 1,
  },
  {
    id: 2,
    category: "Women",
    name: "Ethnic Kurti",
    price: 220,
    inventory: 9,
    img: "././images/product2.png",
    qty: 1,
  },
  {
    id: 3,
    category: "Women",
    name: "Kurtis, Tunics & Tops",
    price: 280,
    inventory: 4,
    img: "././images/product3.png",
    qty: 1,
  },
  {
    id: 4,
    category: "Men",
    name: "Round Neck T-Shirt",
    price: 120,
    inventory: 7,
    img: "././images/product4.png",
    qty: 1,
  },
  {
    id: 5,
    category: "Kids",
    name: "Kurti Full Sleev",
    price: 200,
    inventory: 5,
    img: "././images/trending1.png",
    qty: 1,
  },
  {
    id: 6,
    category: "Women",
    name: "Silk Saree - Printied",
    price: 320,
    inventory: 3,
    img: "././images/trending2.png",
    qty: 1,
  },
  {
    id: 7,
    category: "Men",
    name: "Multi Purpose Jacket",
    price: 510,
    inventory: 6,
    img: "././images/trending3.png",
    qty: 1,
  },
  {
    id: 8,
    category: "Men",
    name: "Jacket",
    price: 400,
    inventory: 11,
    img: "././images/trending4.png",
    qty: 1,
  },
];
